ln -s libopencv_core.so.3.1.0 libopencv_core.so.3.1
ln -s libopencv_core.so.3.1 libopencv_core.so
ln -s libopencv_highgui.so.3.1.0 libopencv_highgui.so.3.1
ln -s libopencv_highgui.so.3.1 libopencv_highgui.so
ln -s libopencv_imgcodecs.so.3.1.0 libopencv_imgcodecs.so.3.1
ln -s libopencv_imgcodecs.so.3.1 libopencv_imgcodecs.so
ln -s libopencv_imgproc.so.3.1.0 libopencv_imgproc.so.3.1
ln -s libopencv_imgproc.so.3.1 libopencv_imgproc.so
ln -s libopencv_videoio.so.3.1.0 libopencv_videoio.so.3.1
ln -s libopencv_videoio.so.3.1 libopencv_videoio.so
ln -s libopencv_video.so.3.1.0 libopencv_video.so.3.1
ln -s libopencv_video.so.3.1 libopencv_video.so